"""add the followers associantion table

Revision ID: 937f4599ae0e
Revises: b00254bc3edf
Create Date: 2025-02-17 16:08:31.558881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '937f4599ae0e'
down_revision = 'b00254bc3edf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
